In [1]:
from __future__ import absolute_import, division, print_function
%matplotlib inline

import os
import glob
import numpy as np
import PIL.Image as pil
import matplotlib.pyplot as plt
from utils import *
from options import MonodepthOptions


%load_ext autoreload
%autoreload 2

In [5]:
intrinsic = np.loadtxt('/home/zhenghaofei/data/kitti/SfmLearner/2011_09_30_drive_0028_sync_03/cam.txt')
print("intrinsic: \n", intrinsic)
image_sample = pil.open('/home/zhenghaofei/data/kitti/SfmLearner/2011_09_30_drive_0028_sync_03/0000004314.jpg')
print("image size: ", image_sample.size)

intrinsic: 
 [[239.92654095   0.         204.22929592]
 [  0.         244.61533405  63.34630054]
 [  0.           0.           1.        ]]
image size:  (416, 128)


In [6]:
intrinsic_normalized = intrinsic.copy()
intrinsic_normalized[0, :] = intrinsic_normalized[0, :] / image_sample.size[0]
intrinsic_normalized[1, :] = intrinsic_normalized[1, :] / image_sample.size[1]
intrinsic_normalized

array([[0.57674649, 0.        , 0.49093581],
       [0.        , 1.9110573 , 0.49489297],
       [0.        , 0.        , 1.        ]])

In [5]:
split_save_path = '/home/zhenghaofei/code/monodepth2/splits/test_custom_data/'

train_data_path = '/home/zhenghaofei/data/kitti/SfmLearner/2011_09_30_drive_0028_sync_03/'
train_fielnames = glob.glob(os.path.join(train_data_path, '*.jpg'))
train_fielnames.sort()



val_data_path = '/home/zhenghaofei/data/kitti/SfmLearner/2011_09_30_drive_0028_sync_03/'
val_fielnames = glob.glob(os.path.join(val_data_path, '*.jpg'))
val_fielnames.sort()

In [16]:
with open(os.path.join(split_save_path, 'train_files.txt'), 'w') as f:
    for idx, train_file in enumerate(train_fielnames):
        f.write(train_file + '\n')

with open(os.path.join(split_save_path, 'val_files.txt'), 'w') as f:
    for idx, val_file in enumerate(val_filenames):
        f.write(val_file + '\n')


In [7]:
import datasets
crop_dataset = datasets.CropRAWDataset


In [8]:
data_path = '/mnt/TempData/people/zhenghao/SfmLearner/mzg/train'
train_filenames = glob.glob(os.path.join(data_path, "*.jpg"))
train_filenames.sort()
height = 128
width = 416
frame_ids = [0, -1, 1]
img_ext = '.jpg'


In [9]:

train_dataset = crop_dataset(
    data_path, train_filenames, height, width,
    frame_ids, 4, is_train=True, img_ext=img_ext)

/home/zhenghaofei/anaconda3/lib/python3.8/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(


In [11]:
i = 0
for a in train_dataset:
    i += 1
    if i > 10:
        break

line:  ['/mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00000000.jpg']
frame index:  0
get_image_path folder /mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00000000.jpg, frame_index 0, side None
image_path:  /mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00000000.jpg
get_image_path folder /mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00000000.jpg, frame_index -1, side None
image_path:  /mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00022995.jpg
get_image_path folder /mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00000000.jpg, frame_index 1, side None
image_path:  /mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00000005.jpg
line:  ['/mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00000005.jpg']
frame index:  1
get_image_path folder /mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00000005.jpg, frame_index 1, side None
image_path:  /mnt/TempData/people/zhenghao/SfmLearner/mzg/train/00000005.jpg
get_image_path folder /mnt/TempData/people/zhenghao/SfmLearne

KITTI

In [8]:
fpath = os.path.join("/home/zhenghaofei/code/monodepth2/splits/eigen_zhou/{}_files.txt")
train_filenames = readlines(fpath.format("train"))
val_filenames = readlines(fpath.format("val"))
img_ext = '.png'
data_path = "/mnt/TempData/openDateset/KITTI/raw/unzip"
height = 192
weight = 640

In [9]:
kitti_dataset = datasets.KITTIRAWDataset
train_dataset = kitti_dataset(
    data_path, train_filenames, height, width,
    frame_ids, 4, is_train=True, img_ext=img_ext)

In [15]:
i = 0
for a in train_dataset:
    i += 1
    if i > 10:
        break